title: David Chan
logo: /assets/img/headshot_circle.png 
description: (515)-829-6295 | davidmchan3@outlook.com | linkedin.com/in/david-chan3 | West Des Moines, IA 
show_downloads: false
theme: jekyll-theme-minimal
